In [4]:
import tensorflow as tf

In [48]:
mnist = tf.keras.datasets.mnist

#Load data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [6]:
#And convert to float
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
#Create neural network
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [8]:
#Test untrained model
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.29659358, -1.2483128 , -0.01258914, -0.9083958 , -0.09044996,
        -0.3696527 ,  0.6248741 , -0.6964865 , -0.16109064,  0.08964382]],
      dtype=float32)

In [9]:
#Convert test output to probability
tf.nn.softmax(predictions).numpy()

array([[0.1504984 , 0.0321061 , 0.11047285, 0.04510365, 0.10219768,
        0.07730095, 0.20897885, 0.05574973, 0.09522746, 0.12236431]],
      dtype=float32)

In [10]:
#Initialize loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
#Calculate loss of test output
loss_fn(y_train[:1], predictions).numpy()

2.560049

In [12]:
#Compile model for training
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
#Train model
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 18s 308us/sample - loss: 0.2951 - accuracy: 0.9147
Epoch 2/5
60000/60000 [==============================] - 17s 287us/sample - loss: 0.1391 - accuracy: 0.9588
Epoch 3/5
60000/60000 [==============================] - 17s 288us/sample - loss: 0.1024 - accuracy: 0.9686
Epoch 4/5
60000/60000 [==============================] - 17s 291us/sample - loss: 0.0866 - accuracy: 0.9730
Epoch 5/5
60000/60000 [==============================] - 18s 292us/sample - loss: 0.0742 - accuracy: 0.9765


In [14]:
#Evaluate model on new data
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 1s - loss: 0.0738 - accuracy: 0.9776


[0.07383366680785548, 0.9776]

In [15]:
#Add probability function to create new model with human output
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [103]:
probability_model(x_test[:5])


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.85932957e-08, 2.01637285e-09, 6.42337739e-07, 2.20677084e-05,
        1.45396778e-10, 8.87182861e-09, 9.34680732e-14, 9.99976516e-01,
        9.32086195e-08, 5.70806492e-07],
       [2.51520731e-07, 1.02205908e-04, 9.99764740e-01, 1.14644565e-04,
        1.13536201e-13, 6.96972029e-06, 2.51364156e-07, 1.41771733e-11,
        1.09055181e-05, 6.47727748e-12],
       [2.96159868e-07, 9.93959904e-01, 1.18538656e-03, 2.20154288e-05,
        8.88907161e-05, 3.63482977e-05, 7.56854424e-05, 3.55387293e-03,
        1.07599131e-03, 1.60116861e-06],
       [9.99774396e-01, 1.11223017e-10, 1.49938103e-06, 4.20883461e-09,
        2.57873694e-07, 2.97212125e-07, 2.22707284e-04, 3.22758297e-07,
        5.70210129e-11, 6.15215072e-07],
       [8.72896749e-07, 4.33424141e-08, 4.17965566e-06, 2.17269882e-08,
        9.99317288e-01, 4.40768218e-07, 1.87189607e-06, 2.45120555e-05,
        4.45026380e-08, 6.50797330e-04]], dtype=float32)>

In [104]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [45]:
from PIL import Image
import numpy as np

In [50]:
Image.fromarray(x_test[0]).show()


In [51]:
i = np.random.randint(0, len(x_test))

Image.fromarray(x_test[i]).show() #x_test must be int so this line works

a = np.ndarray(shape=(1,28,28))
a[0] = x_test[i]

probability_model(a).numpy()

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [52]:
im = Image.open("test.png").convert("L")

a = np.ndarray(shape=(1,28,28))
a[0] = np.asarray(im)# if you add /255 here it shows percentages

probability_model(a).numpy()

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)